const express = require("express");
const app = express();
const cors = require("cors");
require("dotenv").config();
const dbConnect = require("./db/index");
app.use(
  cors({
    origin: "http://localhost:5173",
    credentials: true,
  }),
);
app.use(express.json());
const cookieParser = require("cookie-parser");
app.use(cookieParser());
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");

//middleware *********
const {
  tokenCheck,
  pofileValidet,
  tokenVerify,
} = require("./Middleware/token");

//****Controller**** */
const {
  addOferProduct,
  getOfferData,
} = require("./controller/Admin/offerProductController");

const {
  addCart,
  showCart,
  deleteCart,
} = require("./controller/web/cartController");
const {
  register,
  loginUser,
  profileStutas,
  userLogout,
} = require("./controller/web/userController");
const { getApi } = require("./controller/web/apiController");
const {
  addOrder,
  getOrderDetails,
} = require("./controller/web/productController");
const {
  adminSignup,
  adminLogin,
} = require("./controller/Admin/adminLoginController");

const Eproducts = [
  {
    category: "Smartphones",
    categoryImage: "Xiaomi 13 Pro.jpg",
    products: [
      {
        id: "SP001",
        name: "iPhone 14",
        category: "Smartphones",
        brand: "Apple",
        price: 899.0,
        currency: "USD",
        stock: 50,
        features: ["6.1-inch OLED", "128GB", "A15 Bionic", "Dual Camera"],
        warranty: "1 year",
        rating: 4.7,
        image_url: "iphone-14pro.jpg",
        release_date: "2022-09-16",
      },
      {
        id: "SP002",
        name: "Samsung Galaxy S22",
        category: "Smartphones",
        brand: "Samsung",
        price: 749.0,
        currency: "USD",
        stock: 80,
        features: ["6.1-inch AMOLED", "256GB", "Snapdragon 8", "Triple Camera"],
        warranty: "1 year",
        rating: 4.6,
        image_url: "Samsung Galaxy S22.jpg",
        release_date: "2022-02-25",
      },
      {
        id: "SP003",
        name: "Google Pixel 7",
        category: "Smartphones",
        brand: "Google",
        price: 599.0,
        currency: "USD",
        stock: 60,
        features: ["6.3-inch OLED", "128GB", "Tensor G2", "Dual Camera"],
        warranty: "1 year",
        rating: 4.5,
        image_url: "Google-Pixel-7.jpg",
        release_date: "2022-10-13",
      },
      {
        id: "SP004",
        name: "OnePlus 11",
        category: "Smartphones",
        brand: "OnePlus",
        price: 699.0,
        currency: "USD",
        stock: 45,
        features: [
          "6.7-inch AMOLED",
          "256GB",
          "Snapdragon 8 Gen 2",
          "Triple Camera",
        ],
        warranty: "1 year",
        rating: 4.4,
        image_url: "OnePlus 11.jpg",
        release_date: "2023-02-07",
      },
      {
        id: "SP005",
        name: "Xiaomi 13 Pro",
        category: "Smartphones",
        brand: "Xiaomi",
        price: 799.0,
        currency: "USD",
        stock: 70,
        features: [
          "6.73-inch AMOLED",
          "512GB",
          "Snapdragon 8 Gen 2",
          "Leica Camera",
        ],
        warranty: "1 year",
        rating: 4.3,
        image_url: "Xiaomi 13 Pro.jpg",
        release_date: "2023-03-01",
      },
      {
        id: "SP006",
        name: "Sony Xperia 1 IV",
        category: "Smartphones",
        brand: "Sony",
        price: 999.0,
        currency: "USD",
        stock: 30,
        features: ["4K OLED", "256GB", "Snapdragon 8", "ZEISS Optics"],
        warranty: "1 year",
        rating: 4.2,
        image_url: "SonyXperia1IV.jpg",
        release_date: "2022-06-11",
      },
      {
        id: "SP007",
        name: "Motorola Edge+ (2023)",
        category: "Smartphones",
        brand: "Motorola",
        price: 699.0,
        currency: "USD",
        stock: 40,
        features: [
          "6.7-inch OLED",
          "512GB",
          "Snapdragon 8 Gen 2",
          "Triple Camera",
        ],
        warranty: "1 year",
        rating: 4.3,
        image_url: "motorola-edge-plus-2023.jpg",
        release_date: "2023-05-25",
      },
      {
        id: "SP008",
        name: "Asus ROG Phone 7",
        category: "Smartphones",
        brand: "Asus",
        price: 999.0,
        currency: "USD",
        stock: 25,
        features: [
          "6.78-inch AMOLED",
          "512GB",
          "Snapdragon 8 Gen 2",
          "Gaming Mode",
        ],
        warranty: "1 year",
        rating: 4.6,
        image_url: "Asus ROG Phone 7.png",
        release_date: "2023-04-13",
      },
      {
        id: "SP009",
        name: "Realme GT Neo 5",
        category: "Smartphones",
        brand: "Realme",
        price: 499.0,
        currency: "USD",
        stock: 65,
        features: [
          "6.74-inch AMOLED",
          "256GB",
          "150W Charging",
          "Snapdragon 8+ Gen 1",
        ],
        warranty: "1 year",
        rating: 4.4,
        image_url: "Realme GT Neo 5.webp",
        release_date: "2023-02-09",
      },
      {
        id: "SP010",
        name: "Nothing Phone (2)",
        category: "Smartphones",
        brand: "Nothing",
        price: 599.0,
        currency: "USD",
        stock: 55,
        features: [
          "6.7-inch OLED",
          "Glyph Interface",
          "Snapdragon 8+ Gen 1",
          "Dual Camera",
        ],
        warranty: "1 year",
        rating: 4.5,
        image_url: "Nothing Phone (2).webp",
        release_date: "2023-07-17",
      },
    ],
  },
  {
    category: "Laptops",
    categoryImage: "laptop.jpg",
    products: [
      {
        id: "LP001",
        name: "MacBook Air M2",
        category: "Laptops",
        brand: "Apple",
        price: 1199.0,
        currency: "USD",
        stock: 40,
        features: ["13.6-inch Retina", "M2 Chip", "8GB RAM", "256GB SSD"],
        warranty: "1 year",
        rating: 4.8,
        image_url: "mackbook-air.jpg",
        release_date: "2022-07-15",
      },
      {
        id: "LP002",
        name: "Dell XPS 13",
        category: "Laptops",
        brand: "Dell",
        price: 999.0,
        currency: "USD",
        stock: 30,
        features: ["13.4-inch Display", "Intel i7", "16GB RAM", "512GB SSD"],
        warranty: "1 year",
        rating: 4.6,
        image_url: "dell-xps-13.jpeg",
        release_date: "2023-01-10",
      },
      {
        id: "LP003",
        name: "HP Spectre x360",
        category: "Laptops",
        brand: "HP",
        price: 1149.99,
        currency: "USD",
        stock: 25,
        features: ["13.5-inch Touch", "Intel i7", "16GB RAM", "512GB SSD"],
        warranty: "1 year",
        rating: 4.5,
        image_url: "hp-spectre-x360.jpeg",
        release_date: "2022-11-01",
      },
      {
        id: "LP004",
        name: "Lenovo ThinkPad X1 Carbon",
        category: "Laptops",
        brand: "Lenovo",
        price: 1299.99,
        currency: "USD",
        stock: 20,
        features: ["14-inch Display", "Intel i7", "16GB RAM", "1TB SSD"],
        warranty: "2 years",
        rating: 4.7,
        image_url: "Lenovo-ThinkPad-X1-Carbon.png",
        release_date: "2023-03-12",
      },
      {
        id: "LP005",
        name: "Asus ROG Zephyrus G14",
        category: "Laptops",
        brand: "Asus",
        price: 1499.0,
        currency: "USD",
        stock: 35,
        features: ["14-inch QHD", "Ryzen 9", "16GB RAM", "1TB SSD"],
        warranty: "1 year",
        rating: 4.6,
        image_url: "asus-rog-zephyrus.jpeg",
        release_date: "2023-02-20",
      },
      {
        id: "LP006",
        name: "Microsoft Surface Laptop 5",
        category: "Laptops",
        brand: "Microsoft",
        price: 1299.0,
        currency: "USD",
        stock: 45,
        features: ["13.5-inch Touch", "Intel i7", "16GB RAM", "512GB SSD"],
        warranty: "1 year",
        rating: 4.4,
        image_url: "microsoft-surface-5.jpeg",
        release_date: "2022-10-25",
      },
      {
        id: "LP007",
        name: "Razer Blade 15",
        category: "Laptops",
        brand: "Razer",
        price: 1999.0,
        currency: "USD",
        stock: 15,
        features: ["15.6-inch 240Hz", "Intel i7", "16GB RAM", "1TB SSD"],
        warranty: "1 year",
        rating: 4.5,
        image_url: "laptop-7-Razer Blade 15L.jpg",
        release_date: "2023-04-18",
      },
      {
        id: "LP008",
        name: "Acer Swift X",
        category: "Laptops",
        brand: "Acer",
        price: 899.0,
        currency: "USD",
        stock: 50,
        features: ["14-inch FHD", "Ryzen 7", "16GB RAM", "512GB SSD"],
        warranty: "1 year",
        rating: 4.3,
        image_url: "laptop-8-Acer Swift X.jpg",
        release_date: "2022-08-10",
      },
      {
        id: "LP009",
        name: "MSI Prestige 14",
        category: "Laptops",
        brand: "MSI",
        price: 1099.0,
        currency: "USD",
        stock: 22,
        features: ["14-inch Display", "Intel i7", "16GB RAM", "512GB SSD"],
        warranty: "1 year",
        rating: 4.2,
        image_url: "laptop-9-MSI Prestige 14.jpg",
        release_date: "2023-03-05",
      },
      {
        id: "LP010",
        name: "Samsung Galaxy Book3 Pro",
        category: "Laptops",
        brand: "Samsung",
        price: 1399.0,
        currency: "USD",
        stock: 28,
        features: ["14-inch AMOLED", "Intel i7", "16GB RAM", "1TB SSD"],
        warranty: "1 year",
        rating: 4.4,
        image_url: "laptop-10-samsung Galaxy Book3 Pro.jpg",
        release_date: "2023-02-17",
      },
    ],
  },
  {
    category: "Tablets",
    categoryImage: "tablet.jpg",
    products: [
      {
        id: "TB001",
        name: "iPad Air (5th Gen)",
        category: "Tablets",
        brand: "Apple",
        price: 599.0,
        currency: "USD",
        stock: 60,
        features: ["10.9-inch Liquid Retina", "M1 Chip", "64GB", "Touch ID"],
        warranty: "1 year",
        rating: 4.8,
        image_url: "tablet-1-ipadAir.jpg",
        release_date: "2022-03-18",
      },
      {
        id: "TB002",
        name: "Samsung Galaxy Tab S8",
        category: "Tablets",
        brand: "Samsung",
        price: 699.0,
        currency: "USD",
        stock: 40,
        features: ["11-inch LCD", "128GB", "Snapdragon 8 Gen 1", "S Pen"],
        warranty: "1 year",
        rating: 4.6,
        image_url: "tablet-2-sumsungGalexy.jpg",
        release_date: "2022-02-25",
      },
      {
        id: "TB003",
        name: "Lenovo Tab P12 Pro",
        category: "Tablets",
        brand: "Lenovo",
        price: 649.0,
        currency: "USD",
        stock: 35,
        features: [
          "12.6-inch AMOLED",
          "128GB",
          "Snapdragon 870",
          "Stylus Support",
        ],
        warranty: "1 year",
        rating: 4.5,
        image_url: "tablet-3-lenvo.jpg",
        release_date: "2022-10-01",
      },
      {
        id: "TB004",
        name: "Microsoft Surface Pro 9",
        category: "Tablets",
        brand: "Microsoft",
        price: 999.0,
        currency: "USD",
        stock: 20,
        features: ["13-inch PixelSense", "Intel i5", "256GB SSD", "Windows 11"],
        warranty: "1 year",
        rating: 4.7,
        image_url: "tablet-4-micromax.jpg",
        release_date: "2022-10-25",
      },
      {
        id: "TB005",
        name: "Xiaomi Pad 6",
        category: "Tablets",
        brand: "Xiaomi",
        price: 399.0,
        currency: "USD",
        stock: 45,
        features: ["11-inch 2.8K", "Snapdragon 870", "128GB", "MIUI Pad"],
        warranty: "1 year",
        rating: 4.4,
        image_url: "tablet-5-xiaom--ipad.jpg",
        release_date: "2023-04-18",
      },
      {
        id: "TB006",
        name: "Huawei MatePad Pro 11",
        category: "Tablets",
        brand: "Huawei",
        price: 749.0,
        currency: "USD",
        stock: 25,
        features: ["11-inch OLED", "Snapdragon 870", "HarmonyOS", "128GB"],
        warranty: "1 year",
        rating: 4.2,
        image_url: "camera-6-huaweiMetaPad.jpg",
        release_date: "2022-08-10",
      },
      {
        id: "TB007",
        name: "Realme Pad X",
        category: "Tablets",
        brand: "Realme",
        price: 299.0,
        currency: "USD",
        stock: 50,
        features: [
          "10.95-inch Display",
          "Snapdragon 695",
          "128GB",
          "Dolby Atmos",
        ],
        warranty: "1 year",
        rating: 4.3,
        image_url: "tablet-7-realme-pad11.jpg",
        release_date: "2022-07-26",
      },
      {
        id: "TB008",
        name: "Amazon Fire Max 11",
        category: "Tablets",
        brand: "Amazon",
        price: 229.0,
        currency: "USD",
        stock: 70,
        features: ["11-inch LCD", "64GB", "Octa-core", "Fire OS"],
        warranty: "1 year",
        rating: 4.1,
        image_url: "tablet-8-amazon-fireMax1.jpg",
        release_date: "2023-06-14",
      },
      {
        id: "TB009",
        name: "Apple iPad Pro 12.9 (M2)",
        category: "Tablets",
        brand: "Apple",
        price: 1099.0,
        currency: "USD",
        stock: 30,
        features: ["12.9-inch XDR", "M2 Chip", "256GB", "Face ID"],
        warranty: "1 year",
        rating: 4.9,
        image_url: "tablet-9-applePro.jpg",
        release_date: "2022-10-26",
      },
      {
        id: "TB010",
        name: "Oppo Pad 2",
        category: "Tablets",
        brand: "Oppo",
        price: 459.0,
        currency: "USD",
        stock: 38,
        features: ["11.6-inch LCD", "Dimensity 9000", "256GB", "ColorOS"],
        warranty: "1 year",
        rating: 4.3,
        image_url: "tablet-10-oppo-pad-2.png",
        release_date: "2023-03-21",
      },
    ],
  },
  {
    category: "Smartwatches",
    categoryImage: "smart-watch.jpg",
    products: [
      {
        id: "SW001",
        name: "Apple Watch Series 9",
        category: "Smartwatches",
        brand: "Apple",
        price: 399.0,
        currency: "USD",
        stock: 50,
        features: [
          "Always-On Display",
          "Heart Rate Monitor",
          "Blood Oxygen",
          "watchOS 10",
        ],
        warranty: "1 year",
        rating: 4.8,
        image_url: "apple-watch9series.jpeg",
        release_date: "2023-09-22",
      },
      {
        id: "SW002",
        name: "Samsung Galaxy Watch6",
        category: "Smartwatches",
        brand: "Samsung",
        price: 329.0,
        currency: "USD",
        stock: 40,
        features: ["Super AMOLED", "Sleep Tracking", "ECG", "Wear OS"],
        warranty: "1 year",
        rating: 4.6,
        image_url: "sumsong-galaxy-watch6.jpeg",
        release_date: "2023-08-11",
      },
      {
        id: "SW003",
        name: "Garmin Venu 3",
        category: "Smartwatches",
        brand: "Garmin",
        price: 449.99,
        currency: "USD",
        stock: 35,
        features: ["AMOLED", "Sleep Coaching", "GPS", "Body Battery"],
        warranty: "1 year",
        rating: 4.7,
        image_url: "garmin-venu-3.jpeg",
        release_date: "2023-09-10",
      },
      {
        id: "SW004",
        name: "Fitbit Versa 4",
        category: "Smartwatches",
        brand: "Fitbit",
        price: 229.95,
        currency: "USD",
        stock: 60,
        features: [
          "Heart Rate",
          "Sleep Tracking",
          "Alexa Built-in",
          "6+ Day Battery",
        ],
        warranty: "1 year",
        rating: 4.5,
        image_url: "smartWatch-4-Fitbit Versa 4.jpg",
        release_date: "2022-09-23",
      },
      {
        id: "SW005",
        name: "Amazfit GTR 4",
        category: "Smartwatches",
        brand: "Amazfit",
        price: 199.99,
        currency: "USD",
        stock: 75,
        features: [
          "AMOLED",
          "150+ Sports Modes",
          "Alexa",
          "5 ATM Water Resistance",
        ],
        warranty: "1 year",
        rating: 4.3,
        image_url: "smart-watch-5-Amazfit GTR 4.jpg",
        release_date: "2022-09-15",
      },
      {
        id: "SW006",
        name: "Huawei Watch GT 4",
        category: "Smartwatches",
        brand: "Huawei",
        price: 299.0,
        currency: "USD",
        stock: 45,
        features: [
          "1.43-inch AMOLED",
          "Bluetooth Calling",
          "TruSleep 3.0",
          "Long Battery Life",
        ],
        warranty: "1 year",
        rating: 4.4,
        image_url: "smarwatch-6-Huawei Watch GT 4.jpg",
        release_date: "2023-10-05",
      },
      {
        id: "SW007",
        name: "Google Pixel Watch 2",
        category: "Smartwatches",
        brand: "Google",
        price: 349.0,
        currency: "USD",
        stock: 30,
        features: [
          "Wear OS",
          "Fitbit Integration",
          "Safety Check",
          "Stress Management",
        ],
        warranty: "1 year",
        rating: 4.5,
        image_url: "smartwatch-7-Google Pixel Watch 2.jpg",
        release_date: "2023-10-12",
      },
      {
        id: "SW008",
        name: "OnePlus Watch 2",
        category: "Smartwatches",
        brand: "OnePlus",
        price: 299.0,
        currency: "USD",
        stock: 38,
        features: [
          "Dual Chip Architecture",
          "AMOLED",
          "Wear OS 4",
          "100+ Sports Modes",
        ],
        warranty: "1 year",
        rating: 4.2,
        image_url: "smartwatch-8-OnePlus Watch 2.jpg",
        release_date: "2024-02-26",
      },
      {
        id: "SW009",
        name: "TicWatch Pro 5",
        category: "Smartwatches",
        brand: "Mobvoi",
        price: 349.99,
        currency: "USD",
        stock: 28,
        features: ["Dual Display", "Snapdragon W5+", "Wear OS", "80h Battery"],
        warranty: "1 year",
        rating: 4.4,
        image_url: "smartWatch-9-TicWatch Pro 5.jpg",
        release_date: "2023-05-24",
      },
      {
        id: "SW010",
        name: "Redmi Watch 3 Active",
        category: "Smartwatches",
        brand: "Xiaomi",
        price: 79.99,
        currency: "USD",
        stock: 80,
        features: [
          "1.83-inch Display",
          "Bluetooth Calling",
          "Heart Rate",
          "100+ Fitness Modes",
        ],
        warranty: "1 year",
        rating: 4.1,
        image_url: "smartwatch-10-Redmi Watch 3 Active.jpg",
        release_date: "2023-08-01",
      },
    ],
  },
  {
    category: "Headphones",
    categoryImage: "head-phone.jpg",
    products: [
      {
        id: "HP001",
        name: "Sony WH-1000XM5",
        category: "Headphones",
        brand: "Sony",
        price: 399.99,
        currency: "USD",
        stock: 45,
        features: ["Noise Cancelling", "Wireless", "30h Battery", "LDAC Codec"],
        warranty: "1 year",
        rating: 4.9,
        image_url: "sony-wh-1000xm5.jpeg",
        release_date: "2022-05-20",
      },
      {
        id: "HP002",
        name: "Bose QuietComfort 45",
        category: "Headphones",
        brand: "Bose",
        price: 329.0,
        currency: "USD",
        stock: 50,
        features: ["Noise Cancelling", "Wireless", "24h Battery", "Aware Mode"],
        warranty: "1 year",
        rating: 4.8,
        image_url: "bose-quitComport-45.jpeg",
        release_date: "2022-09-15",
      },
      {
        id: "HP003",
        name: "Apple AirPods Max",
        category: "Headphones",
        brand: "Apple",
        price: 549.0,
        currency: "USD",
        stock: 30,
        features: ["Active Noise Cancellation", "Spatial Audio", "20h Battery"],
        warranty: "1 year",
        rating: 4.7,
        image_url: "apple-airPodas-max.jpeg",
        release_date: "2020-12-15",
      },
      {
        id: "HP004",
        name: "Sennheiser Momentum 4",
        category: "Headphones",
        brand: "Sennheiser",
        price: 349.95,
        currency: "USD",
        stock: 40,
        features: ["Noise Cancelling", "Wireless", "60h Battery", "LDAC"],
        warranty: "1 year",
        rating: 4.6,
        image_url: "sennheiser-momentum-4.jpeg",
        release_date: "2023-04-01",
      },
      {
        id: "HP005",
        name: "Jabra Elite 85h",
        category: "Headphones",
        brand: "Jabra",
        price: 249.99,
        currency: "USD",
        stock: 55,
        features: ["Smart ANC", "Wireless", "36h Battery", "Water Resistant"],
        warranty: "1 year",
        rating: 4.4,
        image_url: "jabra-elite-85h.jpeg",
        release_date: "2019-08-15",
      },
      {
        id: "HP006",
        name: "Beats Studio3",
        category: "Headphones",
        brand: "Beats",
        price: 299.95,
        currency: "USD",
        stock: 35,
        features: [
          "Noise Cancelling",
          "Wireless",
          "22h Battery",
          "Apple W1 Chip",
        ],
        warranty: "1 year",
        rating: 4.3,
        image_url: "headphone-6-Beats Studio3.jpg",
        release_date: "2018-09-25",
      },
      {
        id: "HP007",
        name: "Anker Soundcore Life Q35",
        category: "Headphones",
        brand: "Anker",
        price: 129.99,
        currency: "USD",
        stock: 65,
        features: ["Hybrid ANC", "Wireless", "40h Battery", "Hi-Res Audio"],
        warranty: "1 year",
        rating: 4.2,
        image_url: "Anker-Soundcore-Life-Q35.jpeg",
        release_date: "2021-11-10",
      },
      {
        id: "HP008",
        name: "Bang & Olufsen Beoplay H95",
        category: "Headphones",
        brand: "Bang & Olufsen",
        price: 799.0,
        currency: "USD",
        stock: 15,
        features: [
          "Active Noise Cancellation",
          "Wireless",
          "38h Battery",
          "Luxurious Design",
        ],
        warranty: "1 year",
        rating: 4.7,
        image_url: "headphone-8-Bang & Olufsen Beoplay H95.jpg",
        release_date: "2020-06-20",
      },
      {
        id: "HP009",
        name: "Skullcandy Crusher Evo",
        category: "Headphones",
        brand: "Skullcandy",
        price: 199.99,
        currency: "USD",
        stock: 50,
        features: [
          "Bass Adjustable",
          "Wireless",
          "40h Battery",
          "Rapid Charge",
        ],
        warranty: "1 year",
        rating: 4.1,
        image_url: "headphone-9-Skullcandy Crusher Evo.jpg",
        release_date: "2021-09-15",
      },
      {
        id: "HP010",
        name: "Audio-Technica ATH-M50xBT",
        category: "Headphones",
        brand: "Audio-Technica",
        price: 169.0,
        currency: "USD",
        stock: 55,
        features: [
          "Wireless",
          "45h Battery",
          "Foldable Design",
          "High Fidelity",
        ],
        warranty: "1 year",
        rating: 4.5,
        image_url: "headphone-10-Audio-Technica ATH-M50xBT.jpg",
        release_date: "2020-08-05",
      },
    ],
  },

  {
    category: "Cameras",
    categoryImage: "camera.jpg",
    products: [
      {
        id: "CM001",
        name: "Canon EOS R6 Mark II",
        category: "Cameras",
        brand: "Canon",
        price: 2499.0,
        currency: "USD",
        stock: 20,
        features: [
          "24.2MP Full-Frame",
          "4K60 Video",
          "In-body Image Stabilization",
          "Dual Pixel CMOS AF",
        ],
        warranty: "1 year",
        rating: 4.9,
        image_url: "camera-2-sony.jpg",
        release_date: "2022-11-01",
      },
      {
        id: "CM002",
        name: "Sony Alpha a7 IV",
        category: "Cameras",
        brand: "Sony",
        price: 2799.99,
        currency: "USD",
        stock: 15,
        features: [
          "33MP Full-Frame",
          "4K60 Video",
          "5-axis Stabilization",
          "Real-time Eye AF",
        ],
        warranty: "1 year",
        rating: 4.8,
        image_url: "camera-3-nikon.jpg",
        release_date: "2022-10-15",
      },
      {
        id: "CM003",
        name: "Nikon Z6 II",
        category: "Cameras",
        brand: "Nikon",
        price: 1996.95,
        currency: "USD",
        stock: 18,
        features: [
          "24.5MP Full-Frame",
          "4K Video",
          "Dual EXPEED 6 Processors",
          "In-body Stabilization",
        ],
        warranty: "1 year",
        rating: 4.7,
        image_url: "camera-3-nikon.jpg",
        release_date: "2021-10-14",
      },
      {
        id: "CM004",
        name: "Fujifilm X-T5",
        category: "Cameras",
        brand: "Fujifilm",
        price: 1699.0,
        currency: "USD",
        stock: 25,
        features: [
          "40MP APS-C",
          "6.2K Video",
          "In-body Stabilization",
          "Classic Film Simulation",
        ],
        warranty: "1 year",
        rating: 4.6,
        image_url: "camera-4-fujifilm.jpg",
        release_date: "2022-11-25",
      },
      {
        id: "CM005",
        name: "Panasonic Lumix GH6",
        category: "Cameras",
        brand: "Panasonic",
        price: 2199.99,
        currency: "USD",
        stock: 12,
        features: [
          "25.2MP Micro Four Thirds",
          "5.7K Video",
          "In-body Stabilization",
          "V-Log",
        ],
        warranty: "1 year",
        rating: 4.5,
        image_url: "comera-5-panasonic.jpg",
        release_date: "2022-03-15",
      },
      {
        id: "CM006",
        name: "Olympus OM-D E-M1 Mark III",
        category: "Cameras",
        brand: "Olympus",
        price: 1799.0,
        currency: "USD",
        stock: 20,
        features: [
          "20.4MP Micro Four Thirds",
          "4K Video",
          "5-axis Stabilization",
          "Weather-sealed Body",
        ],
        warranty: "1 year",
        rating: 4.4,
        image_url: "comera-6-olympus.jpg",
        release_date: "2020-02-12",
      },
      {
        id: "CM007",
        name: "Leica Q2",
        category: "Cameras",
        brand: "Leica",
        price: 4995.0,
        currency: "USD",
        stock: 8,
        features: [
          "47.3MP Full-Frame",
          "28mm Fixed Lens",
          "4K Video",
          "Weather-sealed",
        ],
        warranty: "1 year",
        rating: 4.9,
        image_url: "comera-7-leica.jpg",
        release_date: "2019-07-11",
      },
      {
        id: "CM008",
        name: "GoPro HERO12 Black",
        category: "Cameras",
        brand: "GoPro",
        price: 499.99,
        currency: "USD",
        stock: 60,
        features: [
          "5.3K Video",
          "HyperSmooth 7.0",
          "Waterproof",
          "Live Streaming",
        ],
        warranty: "1 year",
        rating: 4.7,
        image_url: "comera-8-goproHero.jpg",
        release_date: "2023-09-15",
      },
      {
        id: "CM009",
        name: "DJI Pocket 2",
        category: "Cameras",
        brand: "DJI",
        price: 349.0,
        currency: "USD",
        stock: 55,
        features: ["64MP Sensor", "4K60 Video", "3-axis Gimbal", "AI Editor"],
        warranty: "1 year",
        rating: 4.5,
        image_url: "camera-9-DJI Pocket 2.jpg",
        release_date: "2020-11-15",
      },
      {
        id: "CM010",
        name: "Canon PowerShot G7 X Mark III",
        category: "Cameras",
        brand: "Canon",
        price: 749.0,
        currency: "USD",
        stock: 30,
        features: [
          "20.1MP 1-inch Sensor",
          "4K Video",
          "Live Streaming",
          "Touchscreen",
        ],
        warranty: "1 year",
        rating: 4.4,
        image_url: "camera-10-Canon PowerShot G7 X Mark III.jpg",
        release_date: "2019-07-22",
      },
      // 10 products
    ],
  },
];

//**************Route******
app.get("/", (req, res) => {
  res.send("welcom to server");
});

//Api data  show
app.get("/api", getApi);

//***************card Route ************

app.post("/addCart", addCart);
app.get("/getCart", tokenVerify, showCart);
app.delete("/deleteCart/:id", tokenVerify, deleteCart);

//******** User route *******
//add user..
app.post("/singup", register);
app.post("/login", tokenCheck, loginUser);
app.get("/profile", pofileValidet, profileStutas); //pofileValid,profileStutas
app.get("/logout", userLogout);

//************Admin routes******/
app.post("/adminLogin", adminLogin);
app.post("/adminSignup", adminSignup);
// app.post("/adminSignup", (req, res) => {
//   res.send("hii");
// });

//******** Product route *******
//Offer Products.....
app.post("/offerProduct", addOferProduct);
app.get("/offerData", getOfferData);

//Order product
app.post("/orderProduct", addOrder);
app.get("/orderDetail", tokenVerify, getOrderDetails);

const PORT = process.env.PORT_NO;
dbConnect().then(() => {
  try {
    app.listen(PORT, () => {
      console.log(`server Runnig to http://localhost/${PORT}..!`);
    });
  } catch (error) {
    console.log("server is runnin field", error);
  }
});
